apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: microservices-ticketing
build:
  local:
    push: false
  artifacts:
  - image: benny0329/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: . 
          src: 'src/**/*.ts'
  - image: benny0329/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: . 
          src: '**/*.js'
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
