apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: microservices-ticketing
build:
  local:
    push: false
  artifacts:
  - image: benny0329/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: . 
          src: 'src/**/*.ts'
  - image: benny0329/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: . 
          src: '**/*.js'
  - image: benny0329/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: . 
          src: '**/*.ts'
  - image: benny0329/orders
    context: orders 
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: . 
          src: '**/*.ts'
  - image: benny0329/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: . 
          src: '**/*.ts'
  - image: benny0329/payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: . 
          src: '**/*.ts'
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
