apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders 
  template:
    metadata:
      labels:
        app: orders 
    spec:
      containers:
      - name: orders 
        image: benny0329/orders
        ports:
        - containerPort: 3000
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: MONGO_URI
            value: 'mongodb://orders-mongo:27017/orders'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key:  JWT_KEY

