apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments 
  template:
    metadata:
      labels:
        app: payments 
    spec:
      containers:
      - name: payments 
        image: benny0329/payments
        ports:
        - containerPort: 3000
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats:4222'
          - name: NATS_CLUSTER_ID
            value: 'ticketing'
          - name: MONGO_URI
            value: 'mongodb://payments-mongo:27017/payments'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key:  JWT_KEY
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: stripe-secret
                key:  STRIPE_KEY
